# Generated by Django 3.2.6 on 2021-08-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TShirtsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='b12fd1a2-c091-4c9b-8f95-c7b292feafef', editable=False, max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('shipping_cost', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('description', models.TextField(max_length=400)),
                ('colors', models.CharField(max_length=100)),
                ('sizes', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
