# Generated by Django 3.2.6 on 2021-08-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('RED', 'RED'), ('WHITE', 'WHITE'), ('BLACK', 'BLACK'), ('ORANGE', 'ORANGE'), ('BROWN', 'BROWN'), ('YELLOW', 'YELLOW'), ('PURPLE', 'PURPLE'), ('PINK', 'PINK'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE')], max_length=100)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=100)),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClothesModel',
            fields=[
                ('code', models.CharField(default='8ce7eca4-80e1-46c7-9c01-db62db4b3378', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('shipping_cost', models.FloatField()),
                ('description', models.TextField(max_length=400)),
                ('category', models.CharField(choices=[('t-shirt', 't-shirt'), ('pants', 'pants'), ('jeans', 'jeans'), ('jackets', 'jackets')], max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ShoesDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('RED', 'RED'), ('WHITE', 'WHITE'), ('BLACK', 'BLACK'), ('ORANGE', 'ORANGE'), ('BROWN', 'BROWN'), ('YELLOW', 'YELLOW'), ('PURPLE', 'PURPLE'), ('PINK', 'PINK'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE')], max_length=100)),
                ('size_number', models.IntegerField()),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoesModel',
            fields=[
                ('code', models.CharField(default='b1a81cf4-d4e8-446f-8440-0b4bff0202a8', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('shipping_cost', models.FloatField()),
                ('availability', models.BooleanField()),
                ('description', models.TextField(max_length=400)),
                ('colors', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='TShirtsModel',
        ),
        migrations.AddField(
            model_name='shoesdetailsmodel',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.shoesmodel'),
        ),
        migrations.AddField(
            model_name='clothesdetailsmodel',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothesmodel'),
        ),
    ]
