# Generated by Django 3.2.6 on 2021-09-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_alter_shoesmodel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoesmodel',
            name='availability',
        ),
    ]
