# Generated by Django 3.2.6 on 2021-08-26 09:57

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=800)),
                ('email', models.EmailField(max_length=100, validators=[main_page.models.validate_email])),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
