# Generated by Django 3.2.6 on 2021-10-03 08:02

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='tel',
            field=models.CharField(max_length=10, validators=[register.models.validate_tel]),
        ),
    ]
